services:
  - type: web
    name: fish_dash_flat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_v2.py
    plan: free
    branch: main
    runtime: python
